name: Overwrite Latest Version
on:
  push:
    branches:
      - latest
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
          cache: "pip"
      - run: pip install -r requirements.txt
      - name: Fetch full gh-pages branch and create user
        run: |
          git fetch origin gh-pages --depth=1
          git config user.name ci-bot
          git config user.email ci-bot@example.com
      - name: Get current latest version number
        run: |
          echo "version=$(mike list stable | grep -oP '\(\K[^\)]+' | cut -d ')' -f 1)" >> $GITHUB_ENV
      - run: echo "${{env.version}}"
