name: Overwrite Latest Version
on:
  push:
    branches:
      - latest
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
          cache: "pip"
      - run: pip install -r requirements.txt
      - name: Fetch full gh-pages branch and create user
        run: |
          git fetch origin gh-pages --depth=1
          git config user.name ci-bot
          git config user.email ci-bot@example.com
      - name: Get current latest version number
        run: |
          content=`mike list latest -j`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          version="fromJson($content).version"
          echo "version=$version" >> $GITHUB_ENV
      - run: mike deploy -p -u ${{ env.version }} latest -t latest
